FROM apache/airflow:2.9.1-python3.11

USER airflow

# Install dbt-postgres and Python libraries for ingestion and testing
RUN pip install --no-cache-dir \
    dbt-core==1.8.2 \
    dbt-postgres==1.8.2 \
    faker==24.0.0 \
    psycopg2-binary==2.9.9 \
    pyyaml==6.0.1 \
    boto3==1.34.0 \
    pandas==2.2.0
